---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: evs.csi.huaweicloud.com
spec:
  attachRequired: {{ .Values.CSIDriver.attachRequired }}
  podInfoOnMount: {{ .Values.CSIDriver.podInfoOnMount }}
  volumeLifecycleModes:
    {{- toYaml .Values.CSIDriver.volumeLifecycleModes | nindent 4 }}
