---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: csi-evs-secret-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-evs-secret-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-evs-controller-sa
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: csi-evs-node-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-evs-secret-role
  apiGroup: rbac.authorization.k8s.io
