{{ $controller := .Values.controller }}
{{ $appLabels := fromYaml (include "app.labels" .) }}
{{ $labels := merge $appLabels $controller.labels }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
{{ toYaml $labels | nindent 4 }}
type: Opaque
data:
{{- if .Values.envSecrets }}
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
